import { v4 as uuidv4 } from 'uuid';

export const DEMO_TRANSACTIONS = [
  {
    id: uuidv4(),
    title: 'Monthly Salary',
    amount: 65000,
    category: 'Salary',
    type: 'income',
    date: '2026-04-01',
    notes: 'April 2026 salary credit',
    recurring: true,
  },
  {
    id: uuidv4(),
    title: 'Freelance Web Project',
    amount: 15000,
    category: 'Freelance',
    type: 'income',
    date: '2026-04-05',
    notes: 'Portfolio website for client',
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'Stock Dividends',
    amount: 3200,
    category: 'Investment',
    type: 'income',
    date: '2026-04-10',
    notes: 'Quarterly dividend payout',
    recurring: true,
  },
  {
    id: uuidv4(),
    title: 'Birthday Gift from Grandma',
    amount: 5000,
    category: 'Gift',
    type: 'income',
    date: '2026-04-14',
    notes: 'Birthday money',
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'House Rent',
    amount: 18000,
    category: 'Rent',
    type: 'expense',
    date: '2026-04-01',
    notes: 'Monthly apartment rent - Koramangala',
    recurring: true,
  },
  {
    id: uuidv4(),
    title: 'Grocery Shopping',
    amount: 4500,
    category: 'Food',
    type: 'expense',
    date: '2026-04-02',
    notes: 'Weekly groceries from BigBasket',
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'Zomato Orders',
    amount: 2800,
    category: 'Food',
    type: 'expense',
    date: '2026-04-04',
    notes: 'Multiple food delivery orders this week',
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'Netflix Subscription',
    amount: 649,
    category: 'Subscriptions',
    type: 'expense',
    date: '2026-04-03',
    notes: 'Monthly Netflix premium plan',
    recurring: true,
  },
  {
    id: uuidv4(),
    title: 'Spotify Premium',
    amount: 119,
    category: 'Subscriptions',
    type: 'expense',
    date: '2026-04-03',
    notes: 'Music streaming subscription',
    recurring: true,
  },
  {
    id: uuidv4(),
    title: 'Electricity Bill',
    amount: 2200,
    category: 'Utilities',
    type: 'expense',
    date: '2026-04-05',
    notes: 'March electricity bill',
    recurring: true,
  },
  {
    id: uuidv4(),
    title: 'WiFi Bill',
    amount: 999,
    category: 'Utilities',
    type: 'expense',
    date: '2026-04-05',
    notes: 'Airtel Fiber broadband',
    recurring: true,
  },
  {
    id: uuidv4(),
    title: 'Weekend Trip to Coorg',
    amount: 8500,
    category: 'Travel',
    type: 'expense',
    date: '2026-04-07',
    notes: 'Road trip with friends - fuel, stay, food',
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'New Running Shoes',
    amount: 5499,
    category: 'Shopping',
    type: 'expense',
    date: '2026-04-08',
    notes: 'Nike Air Zoom from Myntra',
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'Movie Night',
    amount: 850,
    category: 'Entertainment',
    type: 'expense',
    date: '2026-04-09',
    notes: 'Two tickets + popcorn at PVR',
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'Gym Membership',
    amount: 2500,
    category: 'Health',
    type: 'expense',
    date: '2026-04-01',
    notes: 'Monthly gym membership - Cult.fit',
    recurring: true,
  },
  {
    id: uuidv4(),
    title: 'Doctor Visit',
    amount: 800,
    category: 'Health',
    type: 'expense',
    date: '2026-04-12',
    notes: 'General health checkup',
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'Uber Rides',
    amount: 1650,
    category: 'Travel',
    type: 'expense',
    date: '2026-04-11',
    notes: 'Week commute rides',
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'Amazon Prime',
    amount: 1499,
    category: 'Subscriptions',
    type: 'expense',
    date: '2026-04-15',
    notes: 'Annual Prime membership (monthly split)',
    recurring: true,
  },
  {
    id: uuidv4(),
    title: 'Coffee & Snacks',
    amount: 1200,
    category: 'Food',
    type: 'expense',
    date: '2026-04-13',
    notes: 'Third Wave Coffee visits',
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'T-shirt Purchase',
    amount: 1299,
    category: 'Shopping',
    type: 'expense',
    date: '2026-04-16',
    notes: 'Casual wear from Bewakoof',
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'March Salary',
    amount: 65000,
    category: 'Salary',
    type: 'income',
    date: '2026-03-01',
    notes: 'March 2026 salary credit',
    recurring: true,
  },
  {
    id: uuidv4(),
    title: 'March Rent',
    amount: 18000,
    category: 'Rent',
    type: 'expense',
    date: '2026-03-01',
    notes: 'Monthly apartment rent',
    recurring: true,
  },
  {
    id: uuidv4(),
    title: 'March Groceries',
    amount: 5200,
    category: 'Food',
    type: 'expense',
    date: '2026-03-04',
    notes: 'Monthly grocery shopping',
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'March Travel',
    amount: 3500,
    category: 'Travel',
    type: 'expense',
    date: '2026-03-10',
    notes: 'Local travel expenses',
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'March Entertainment',
    amount: 2000,
    category: 'Entertainment',
    type: 'expense',
    date: '2026-03-15',
    notes: 'Movies and dining out',
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'February Salary',
    amount: 65000,
    category: 'Salary',
    type: 'income',
    date: '2026-02-01',
    notes: 'February 2026 salary credit',
    recurring: true,
  },
  {
    id: uuidv4(),
    title: 'Feb Rent',
    amount: 18000,
    category: 'Rent',
    type: 'expense',
    date: '2026-02-01',
    notes: 'Monthly apartment rent',
    recurring: true,
  },
  {
    id: uuidv4(),
    title: 'Feb Groceries',
    amount: 4800,
    category: 'Food',
    type: 'expense',
    date: '2026-02-05',
    notes: 'Monthly grocery shopping',
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'Feb Shopping',
    amount: 7500,
    category: 'Shopping',
    type: 'expense',
    date: '2026-02-14',
    notes: "Valentine's day shopping",
    recurring: false,
  },
  {
    id: uuidv4(),
    title: 'January Salary',
    amount: 62000,
    category: 'Salary',
    type: 'income',
    date: '2026-01-01',
    notes: 'January 2026 salary credit',
    recurring: true,
  },
  {
    id: uuidv4(),
    title: 'Jan Rent',
    amount: 18000,
    category: 'Rent',
    type: 'expense',
    date: '2026-01-01',
    notes: 'Monthly apartment rent',
    recurring: true,
  },
  {
    id: uuidv4(),
    title: 'Jan Utilities',
    amount: 3800,
    category: 'Utilities',
    type: 'expense',
    date: '2026-01-08',
    notes: 'Electricity + Internet + Gas',
    recurring: false,
  },
];

export const DEMO_BUDGET = {
  monthlyBudget: 50000,
};
